GLOB sdist-make: /code/modules/weko-theme/setup.py
c1 inst-nodeps: /code/modules/weko-theme/.tox/.tmp/package/1/weko-theme-0.1.0.dev20170000.zip
ERROR: invocation failed (exit code 1), logfile: /code/modules/weko-theme/.tox/c1/log/c1-5.log
================================== log start ===================================
Processing ./.tox/.tmp/package/1/weko-theme-0.1.0.dev20170000.zip
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /code/modules/weko-theme/.tox/c1/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/tmp/pip-req-build-n29ogr37/setup.py'"'"'; __file__='"'"'/var/tmp/pip-req-build-n29ogr37/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /var/tmp/pip-pip-egg-info-f9578to7
       cwd: /var/tmp/pip-req-build-n29ogr37/
  Complete output (37 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/pytest-runner/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/pytest-runner/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/pytest-runner/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/pytest-runner/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/pytest-runner/
  ERROR: Could not find a version that satisfies the requirement pytest-runner<5,>=3.0.0 (from versions: none)
  ERROR: No matching distribution found for pytest-runner<5,>=3.0.0
  Traceback (most recent call last):
    File "/code/modules/weko-theme/.tox/c1/lib/python3.6/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
      subprocess.check_call(cmd)
    File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/code/modules/weko-theme/.tox/c1/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/tmp/tmp3eruuwbn', '--quiet', 'pytest-runner<5,>=3.0.0']' returned non-zero exit status 1.
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/var/tmp/pip-req-build-n29ogr37/setup.py", line 121, in <module>
      'Development Status :: 1 - Planning',
    File "/code/modules/weko-theme/.tox/c1/lib/python3.6/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/code/modules/weko-theme/.tox/c1/lib/python3.6/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/code/modules/weko-theme/.tox/c1/lib/python3.6/site-packages/setuptools/dist.py", line 788, in fetch_build_eggs
      replace_conflicting=True,
    File "/code/modules/weko-theme/.tox/c1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 768, in resolve
      replace_conflicting=replace_conflicting
    File "/code/modules/weko-theme/.tox/c1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1051, in best_match
      return self.obtain(req, installer)
    File "/code/modules/weko-theme/.tox/c1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1063, in obtain
      return installer(requirement)
    File "/code/modules/weko-theme/.tox/c1/lib/python3.6/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/code/modules/weko-theme/.tox/c1/lib/python3.6/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['/code/modules/weko-theme/.tox/c1/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/tmp/tmp3eruuwbn', '--quiet', 'pytest-runner<5,>=3.0.0']' returned non-zero exit status 1.
  ----------------------------------------
WARNING: Discarding file:///code/modules/weko-theme/.tox/.tmp/package/1/weko-theme-0.1.0.dev20170000.zip. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

=================================== log end ====================================
___________________________________ summary ____________________________________
ERROR:   c1: InvocationError for command /code/modules/weko-theme/.tox/c1/bin/python -m pip install --no-deps -U .tox/.tmp/package/1/weko-theme-0.1.0.dev20170000.zip (exited with code 1)
